# Generated by Django 4.0.3 on 2022-06-26 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userss', '0004_alter_worker_scheldue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='reservation',
        ),
        migrations.AlterField(
            model_name='scheldue',
            name='end_break',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scheldue',
            name='start_break',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_reserv', models.TimeField()),
                ('end_reserv', models.TimeField()),
                ('day', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userss.client')),
            ],
        ),
    ]
