# Generated by Django 4.0.3 on 2022-06-27 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userss', '0006_reservation_docid'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='procedure',
            field=models.CharField(choices=[('Consultation', 'Consultation'), ('Operation', 'Operation')], default=('Operation', 'Operation'), max_length=50),
        ),
    ]
