# Generated by Django 4.0.3 on 2022-06-27 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userss', '0008_alter_reservation_client_alter_reservation_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userss.client'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='day',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='end_reserv',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start_reserv',
            field=models.TimeField(),
        ),
    ]
