# Generated by Django 4.0.3 on 2022-06-27 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userss', '0010_alter_reservation_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userss.client'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='docid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userss.worker'),
        ),
    ]
